#!/bin/sh

# change this to your libasm folder
export LIBASM_FOLDER=../../

# ONLY CHANGE IF THE GODS HAVE DECIDED TO USE PROPER FOLDERS
export LIBASM_INC=$LIBASM_FOLDER/inc

# amount of times smokebreak will try to fuck with your code before giving up
export SMOKEBREAK_MAX=25

# DEBUG INTERNALS
export NAME=run-test
export EXEC=./$NAME
